;/*FB_PKG_DELIM*/

__d("CometFeedStoryPageAdminAttributionStrategy_adminAttribution.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometFeedStoryPageAdminAttributionStrategy_adminAttribution",selections:[{args:null,kind:"FragmentSpread",name:"useCometFeedStoryMatchDebugger_iCometStorySection"},{alias:null,args:null,concreteType:"TextWithEntities",kind:"LinkedField",name:"attribution_text",plural:!1,selections:[{args:null,kind:"FragmentSpread",name:"CometTextWithEntitiesRelay_textWithEntities"}],storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"tooltip_icon",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"tooltip_text",storageKey:null}],type:"CometStoryPageAdminAttributionStrategy",abstractKey:null};e.exports=a}),null);
__d("CometFeedStoryPageAdminAttributionStrategy.react",["CometFeedStoryPageAdminAttributionStrategy_adminAttribution.graphql","CometHovercardEntityRenderer","CometImage.react","CometLinkedEntityRenderer","CometRelay","CometTextWithEntitiesRelay.react","CometTrackingNodeRenderer","FDSTooltip.react","react","react-compiler-runtime","unrecoverableViolation","useCometFeedStoryMatchDebugger"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react"),k={badge:{marginBottom:"x1jyxor1",paddingStart:"x1e558r4",$$css:!0}};function a(a){var e=d("react-compiler-runtime").c(11);a=a.adminAttribution;a=d("CometRelay").useFragment(h!==void 0?h:h=b("CometFeedStoryPageAdminAttributionStrategy_adminAttribution.graphql"),a);c("useCometFeedStoryMatchDebugger")(a);var f=a.attribution_text,g=a.tooltip_icon;a=a.tooltip_text;if(f==null||g==null||a==null)throw c("unrecoverableViolation")("post attribution text cannot be null in CometFeedPageAdminAttributionStrategy","pages_consumer_experience_www");var i;e[0]===Symbol["for"]("react.memo_cache_sentinel")?(i={User:[c("CometLinkedEntityRenderer"),c("CometHovercardEntityRenderer"),c("CometTrackingNodeRenderer")]},e[0]=i):i=e[0];e[1]!==f?(i=j.jsx(c("CometTextWithEntitiesRelay.react"),{renderers:i,textWithEntities:f}),e[1]=f,e[2]=i):i=e[2];e[3]!==g?(f=j.jsx(c("CometImage.react"),{height:12,src:g,width:12,xstyle:k.badge}),e[3]=g,e[4]=f):f=e[4];e[5]!==f||e[6]!==a?(g=j.jsx(c("FDSTooltip.react"),{tooltip:a,children:f}),e[5]=f,e[6]=a,e[7]=g):g=e[7];e[8]!==i||e[9]!==g?(f=j.jsxs(j.Fragment,{children:[i,g]}),e[8]=i,e[9]=g,e[10]=f):f=e[10];return f}g["default"]=a}),98);
__d("CometFeedStoryPageAdminAttributionStrategy_adminAttribution$normalization.graphql",["CometTextWithEntitiesRelay_textWithEntities$normalization.graphql"],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"CometFeedStoryPageAdminAttributionStrategy_adminAttribution$normalization",selections:[{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"is_prod_eligible",storageKey:null}],type:"ICometStorySection",abstractKey:"__isICometStorySection"},{alias:null,args:null,concreteType:"TextWithEntities",kind:"LinkedField",name:"attribution_text",plural:!1,selections:[{args:null,fragment:b("CometTextWithEntitiesRelay_textWithEntities$normalization.graphql"),kind:"FragmentSpread"}],storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"tooltip_icon",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"tooltip_text",storageKey:null}]};e.exports=a}),null);
__d("LWICometContextualDataContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=null;c=a.createContext(b);g["default"]=c}),98);
__d("LWICometSpecContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({current:Object.freeze({}),history:[]});g["default"]=b}),98);
__d("SBAGraduationCreationPackageTypeEnums",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({ADVANTAGE_SHOPPING_CAMPAIGNS:"advantage_shopping_campaigns",ENGAGEMENT:"engagement",LEAD_GEN:"lead_gen",WEB_TRAFFIC:"web_traffic"});c=a;f["default"]=c}),66);
__d("XFBSBAGraduationCreationPackageTypeEnumsUtils.facebook",["$InternalEnumUtils","SBAGraduationCreationPackageTypeEnums"],(function(a,b,c,d,e,f,g){a=d("$InternalEnumUtils").createToJSEnum(c("SBAGraduationCreationPackageTypeEnums"));b=d("$InternalEnumUtils").createFromJSEnum(c("SBAGraduationCreationPackageTypeEnums"));g.toJSEnum=a;g.fromJSEnum=b}),98);
__d("updateLWIGraduationStateToGraduatingMutation",["updateLWIGraduationStateToGraduatingMutation.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h!==void 0?h:h=b("updateLWIGraduationStateToGraduatingMutation.graphql");c=a;g["default"]=c}),98);
__d("useLWICometCurrentSpec",["LWICometSpecContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){return i(c("LWICometSpecContext")).current}g["default"]=a}),98);
__d("useLWILoggerContext",["LWICometLoggerContext","react","unrecoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){var a=i(c("LWICometLoggerContext"));if(a==null)throw c("unrecoverableViolation")("LWI logger context must be set for LWI product flows","pages_lwi");return a}g["default"]=a}),98);
__d("withLWICometSpecPart",["LWICometSpecContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react")),j=h.useContext;function a(a,b){var e=i.memo(a);function f(a){var f=d("react-compiler-runtime").c(9),g,h;f[0]!==a?(h=a.ref,g=babelHelpers.objectWithoutPropertiesLoose(a,["ref"]),f[0]=a,f[1]=g,f[2]=h):(g=f[1],h=f[2]);a=j(c("LWICometSpecContext"));var k;f[3]!==a.current?(k=b(a.current),f[3]=a.current,f[4]=k):k=f[4];a=k;f[5]!==a||f[6]!==g||f[7]!==h?(k=i.jsx(e,babelHelpers["extends"]({},g,a,{ref:h})),f[5]=a,f[6]=g,f[7]=h,f[8]=k):k=f[8];return k}return f}g["default"]=a}),98);